apiVersion: v1
kind: Pod
metadata:
  name: configured-pod
spec:
  containers:
    - image: nginx:1.19.0
      name: app
      volumeMounts:
        - name: db-config
          mountPath: /etc/config

  volumes:
    - name: db-config
      configMap:
        name: db-config
