apiVersion: v1
kind: Pod
metadata:
  name: consumer
spec:
  containers:
    - image: nginx:1.19.0
      name: app
      volumeMounts:
        - name: secret-volume
          mountPath: /var/app
      env:
        - name: API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: ext-service-configmap
              key: api_endpoint
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: ext-service-configmap
              key: username
  volumes:
    - name: secret-volume
      secret:
        secretName: ext-service-secret
