apiVersion: v1
kind: Pod
metadata:
  name: consumer
spec:
  containers:
    - image: nginx:1.19.0
      name: app
      volumeMounts:
        - name: secret-volume
          mountPath: /var/app
  volumes:
    - name: secret-volume
      secret:
        secretName: ext-service-secret
