apiVersion: v1
kind: Pod
metadata:
  name: loop
  labels:
    name: loop
spec:
  containers:
    - name: loop
      image: busybox
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
      ports:
        - containerPort: 81
