apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  containers:
    - image: alpine
      name: app
      securityContext:
        capabilities:
          add: ['SYS_TIME']
  restartPolicy: Never
