apiVersion: v1
kind: Pod
metadata:
  name: complex-pod
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: [/bin/sh, -c, 'wget -O- google.com']
  containers:
  - name: app
    image: nginx
    ports:
    - containerPort: 80
  restartPolicy: Never