apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: data-exchange
  name: data-exchange
spec:
  containers:
  - image: busybox
    name: main-app
    command: ["sh", "-c", 'counter=0; while true; do touch "/var/app/data/$((++counter))-data.txt"; sleep 30; done;']
    resources: {}
    volumeMounts:
    - name: data-volume
      mountPath: /var/app/data
  - image: busybox
    name: sidecar
    command: ["sh", "-c", 'while true; do echo "$(ls /var/app/data/*-data.txt | wc -l)"; sleep 60; done;']
    resources: {}
    volumeMounts:
    - name: data-volume
      mountPath: /var/app/data
  volumes:
  - name: data-volume
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
