apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: logs-vol
          mountPath: /var/log/nginx
    - name: sidecar
      image: busybox:1.32.0
      command:
        [
          "sh",
          "-c",
          "while true; do if [ \"$(cat /var/log/nginx/error.log | grep 'error')\" != \"\" ]; then echo 'Error discovered!'; fi; sleep 10; done"
        ]
      volumeMounts:
        - name: logs-vol
          mountPath: /var/log/nginx
  volumes:
    - name: logs-vol
      emptyDir: {}
