apiVersion: batch/v1
kind: Job
metadata:
  name: counter
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: counter
        image: nginx
        command:
        - bin/bash
        - -c
        - counter=0; while [ $counter -lt 3 ]; do echo $((++counter)); sleep 3; done  
