apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-depl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-depl
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
