apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-depl
  labels:
    app: my-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-depl
  template:
    metadata:
      labels:
        app: my-depl
    spec:
      containers:
      - name: nginx
        image: nginx
