apiVersion: v1
kind: Pod
metadata:
  name: app-consuming-pvc
spec:
  containers:
  - name: app
    image: alpine
    command: 
    - /bin/sh
    - -c
    - while true; do sleep 60; done;
    volumeMounts:
    - name: app-storage
      mountPath: /mnt/data
  volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: db-pvc
