apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: logs-volume
      mountPath: /var/logs
  volumes:
  - name: logs-volume
    emptyDir: {}
