apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: logs-volume
      mountPath: /var/logs/nginx
  volumes:
  - name: logs-volume
    persistentVolumeClaim:
       claimName: logs-pvc
