apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
  - name: app
    image: nginx
    ports:
    - name: nodejs-port
      containerPort: 80
    startupProbe:
      httpGet:
        path: /
        port: nodejs-port
    readinessProbe:
      httpGet:
        path: /
        port: nodejs-port
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: nodejs-port
      initialDelaySeconds: 10
      periodSeconds: 30  

